"""initial migration

Revision ID: 141958f945b9
Revises: 
Create Date: 2024-02-08 21:45:20.313425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141958f945b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('DoctorID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('Specialization', sa.String(length=50), nullable=True),
    sa.Column('ContactNumber', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('DoctorID')
    )
    op.create_table('laboratory_technician',
    sa.Column('LabTechID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('Specialization', sa.String(length=50), nullable=True),
    sa.Column('ContactNumber', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('LabTechID')
    )
    op.create_table('manager',
    sa.Column('ManagerID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('ContactNumber', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ManagerID')
    )
    op.create_table('nurse',
    sa.Column('NurseID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('Specialization', sa.String(length=50), nullable=True),
    sa.Column('ContactNumber', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('NurseID')
    )
    op.create_table('patient',
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('ContactNumber', sa.String(length=15), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PatientID')
    )
    op.create_table('receptionist',
    sa.Column('ReceptionistID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('ContactNumber', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ReceptionistID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='email_unique_constraint'),
    sa.UniqueConstraint('username', name='user_unique_constraint')
    )
    op.create_table('appointment',
    sa.Column('AppointmentID', sa.Integer(), nullable=False),
    sa.Column('ReceptionistID', sa.Integer(), nullable=True),
    sa.Column('PatientID', sa.Integer(), nullable=True),
    sa.Column('AppointmentDate', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], name=op.f('fk_appointment_PatientID_patient')),
    sa.ForeignKeyConstraint(['ReceptionistID'], ['receptionist.ReceptionistID'], name=op.f('fk_appointment_ReceptionistID_receptionist')),
    sa.PrimaryKeyConstraint('AppointmentID')
    )
    op.create_table('consultation',
    sa.Column('ConsultationID', sa.Integer(), nullable=False),
    sa.Column('NurseID', sa.Integer(), nullable=True),
    sa.Column('DoctorID', sa.Integer(), nullable=True),
    sa.Column('PatientID', sa.Integer(), nullable=True),
    sa.Column('ConsultationDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['DoctorID'], ['doctor.DoctorID'], name=op.f('fk_consultation_DoctorID_doctor')),
    sa.ForeignKeyConstraint(['NurseID'], ['nurse.NurseID'], name=op.f('fk_consultation_NurseID_nurse')),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], name=op.f('fk_consultation_PatientID_patient')),
    sa.PrimaryKeyConstraint('ConsultationID')
    )
    op.create_table('lab_test',
    sa.Column('TestID', sa.Integer(), nullable=False),
    sa.Column('LabTechID', sa.Integer(), nullable=True),
    sa.Column('PatientID', sa.Integer(), nullable=True),
    sa.Column('DoctorID', sa.Integer(), nullable=True),
    sa.Column('TestName', sa.String(length=100), nullable=True),
    sa.Column('TestDate', sa.DateTime(), nullable=True),
    sa.Column('Results', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['DoctorID'], ['doctor.DoctorID'], name=op.f('fk_lab_test_DoctorID_doctor')),
    sa.ForeignKeyConstraint(['LabTechID'], ['laboratory_technician.LabTechID'], name=op.f('fk_lab_test_LabTechID_laboratory_technician')),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], name=op.f('fk_lab_test_PatientID_patient')),
    sa.PrimaryKeyConstraint('TestID')
    )
    op.create_table('payment',
    sa.Column('PaymentID', sa.Integer(), nullable=False),
    sa.Column('PatientID', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Float(), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('PaymentStatus', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], name=op.f('fk_payment_PatientID_patient')),
    sa.PrimaryKeyConstraint('PaymentID')
    )
    op.create_table('pharmacist',
    sa.Column('PharmacistID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('ContactNumber', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('DoctorID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DoctorID'], ['doctor.DoctorID'], name=op.f('fk_pharmacist_DoctorID_doctor')),
    sa.PrimaryKeyConstraint('PharmacistID')
    )
    op.create_table('medication',
    sa.Column('MedicationID', sa.Integer(), nullable=False),
    sa.Column('PharmacistID', sa.Integer(), nullable=True),
    sa.Column('PatientID', sa.Integer(), nullable=True),
    sa.Column('DoctorID', sa.Integer(), nullable=True),
    sa.Column('MedicationName', sa.String(length=100), nullable=True),
    sa.Column('DispenseDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['DoctorID'], ['doctor.DoctorID'], name=op.f('fk_medication_DoctorID_doctor')),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], name=op.f('fk_medication_PatientID_patient')),
    sa.ForeignKeyConstraint(['PharmacistID'], ['pharmacist.PharmacistID'], name=op.f('fk_medication_PharmacistID_pharmacist')),
    sa.PrimaryKeyConstraint('MedicationID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication')
    op.drop_table('pharmacist')
    op.drop_table('payment')
    op.drop_table('lab_test')
    op.drop_table('consultation')
    op.drop_table('appointment')
    op.drop_table('users')
    op.drop_table('receptionist')
    op.drop_table('patient')
    op.drop_table('nurse')
    op.drop_table('manager')
    op.drop_table('laboratory_technician')
    op.drop_table('doctor')
    # ### end Alembic commands ###
